#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := httpSettingsEditor
EXTRA_COMPONENT_DIRS := D:/Projekte/33_ESP32_Projects/components

include $(IDF_PATH)/make/project.mk

